<div id="content">
    <input id="activityNameInput" placeholder="title" class="bottomsheet-content-item">
    <textarea id="descriptionInput" placeholder="descrption" class="bottomsheet-content-item"></textarea>
    <duration-picker id="timeInput" class="bottomsheet-content-item"></duration-picker>
    <input id="addPhoto" type="file" accept="image/jpeg, image/png, image/jpg,image/gif" multiple="" class="bottomsheet-content-item">
    <tag-input id="tag"></tag-input>
</div>
