<div>
  <div id="user-group" style="display: flex;width: 90vw;justify-content: center;padding: 2vh 2vw;background-color: var(--foreground-color);border: 0.5vw var(--border-colour) solid;margin: 1vh 0vw;border-radius: 5vw;">
  <h1 id="welcome-message" class="menu-title"></h1>
  <button id="sign-out"style="width: 34vw;">sign out</button>
  </div>
  <div id="themes" style="display: flex;width: 90vw;justify-content: center;padding: 2vh 2vw;background-color: var(--foreground-color);border: 0.5vw var(--border-colour) solid;margin: 1vh 0vw;border-radius: 5vw;">
  <button id="light-theme"style="width: 34vw;">light theme</button>
  <button id="dark-theme"style="width: 34vw;">dark theme</button>
  </div>

<div>
