<li style="display: flex; overflow-wrap: anywhere; flex-direction: row; width: 90vw; border: 0.5vw solid var(--border-colour); border-radius: 3vw; padding: 2vw 1vw;margin: 1vh 0vw;">
  <div style="width: 80%;justify-content: center;align-items: center;display: flex;flex-direction: column;">
  <h2 id="entry-title" style="width: 75%;justify-content: center;padding: 1vh 1vw;" data-id="" class="menu-item"></h2>
  <h3 id="duration"></h3>
  </div>
  <div>
    <button id="edit">edit ✏️</button>
    <button id="start" style="display: none;text-align: center;justify-content: center;align-items: center;">start ▶️</button>
  </div>

</li>
