<ul id="entryThumbnail" style="display: flex; border: 0.5vw solid black; border-radius: 5vw; flex-direction: column; overflow-wrap: anywhere; width: 75vw; place-content: center; padding: 2vh 2vw;">
  <img id="image" src="" style="object-fit: contain;border-radius: 6vw;">
  <h3 id="title" style="margin-bottom: 0px; text-align: center;"></h3>
  <p id="description" style="margin: 0px; text-align: center;"></p>
  <ul style="display: flex; justify-content: space-around; margin: 0px; padding: 0px; height: 10vh; text-align: center; font-size: 8vw;">
    <p id="duration" ></p>
    <button style="align-self: center; font-size: 9vw; background-color: var(--button-colour); padding: 1vw; border: 1px; border-radius: 2vw; margin: 2vw; width: 26vw;">edit</button>
  </ul>
</ul>
