<ul style="justify-content: space-between; display: flex; flex-direction: row;" data-id="" class="bottomsheet-content-item draggable activty-item" draggable="true">
  <div style="display: flex;width: 80%;" >
    <img style="display: none; width: 29%; object-fit: contain;padding: 0vh 1.5vw;border-radius: 3vw;"></img>
    <h2></h2>
  </div>
  <div style="display:flex;flex-direction: row;align-items: center;">
    <p id="duration" style="align-self: flex-end; overflow-wrap: anywhere;"></p>
    <h4>🗑️</h4>
    <p id="drag">⋮⋮</p>
  <div>
</ul>
