<ul style="justify-content: space-between; display: flex; flex-direction: row;padding: 1vh 2.5vw;margin: 1vh 2vw;" data-id="" class="bottomsheet-content-item draggable activty-item" draggable="true">
  <div style="display: flex;width: 80%;" >
    <img style="display: none; width: 29%; object-fit: contain;padding: 0vh 1.5vw;border-radius: 3vw;"></img>
    <h2 style="display: flex;align-self: center;width: 50%;overflow-wrap: anywhere;"></h2>
  </div>
  <div style="display:flex;flex-direction: row;align-items: center;">
    <h4>🗑️</h4>
    <p id="duration" style=" overflow-wrap: anywhere;"></p>
    <p id="drag" style="font-size: 9vw;padding: 0vh 3vw;margin:0;">⋮⋮</p>
  <div>
</ul>
