<div id="container">
  <li style="justify-content: space-between;" id="setContainer" class="bottomsheet-content-item">
    <p>number of sets</p>
    <input id="set-input" type="number" style="font-size: 5vw; width: 12vw;" placeholder="num">
  </li>
  <li style="justify-content: space-between;" id="restTimerContainer" class="bottomsheet-content-item">
    <p>rest between exercises</p>
    <input id="rest-timer-input" type="time" step="600" style="font-size: 5vw;">
  </li>
    <li style="justify-content: space-between;" id="setRestContainer" class="bottomsheet-content-item">
    <p>rest between sets</p>
    <input id="set-rest-input" type="time" step="600" style="font-size: 5vw;">
  </li>
</div>
