<div id="container">
  <button type="button" class="bottomsheet-content-item" id="create-empty-playlist">
    create empty playlist
  </button>
  <label for="import-playlist-input" type="button" class="bottomsheet-content-item" id="import-playlist" style="background-color: var(--button-colour);">
    import playlist
  </label>
  <input id="playlist-title" class="bottomsheet-content-item" style="display: none;" placeholder="workout name">
  <input id="import-playlist-input" style="display: none;" type="file" >
</div>
